# Generated by Django 5.1.5 on 2025-01-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aunth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=35)),
                ('role', models.CharField(default='user', max_length=35)),
            ],
        ),
        migrations.DeleteModel(
            name='worker',
        ),
    ]
