# Generated by Django 5.1.5 on 2025-01-18 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_product_alter_aunth_name_alter_aunth_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name1',
        ),
    ]
