# Generated by Django 5.1.5 on 2025-01-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_rename_name_product_name1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='art',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(),
        ),
    ]
