# Generated by Django 5.1.5 on 2025-01-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='data_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
