# Generated by Django 5.1.5 on 2025-01-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_alter_orders_data_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='data_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payment',
            field=models.CharField(choices=[('Банк', 'Банк'), ('Наличные', 'Наличные'), ('Должник', 'Должник')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
